export const products = [
  { emoji: "🍌", unitWeight: 0.12, id: "banana", name: "Banana" },
  { emoji: "🍎", unitWeight: 0.195, id: "apple_red", name: "Manzana roja" },
  { emoji: "🍏", unitWeight: 0.195, id: "apple_green", name: "Manzana verde" },
  { emoji: "🍑", unitWeight: 0.15, id: "peach_white", name: "Durazno blanco" },
  {
    emoji: "🍑",
    unitWeight: 0.15,
    id: "peach_yellow",
    name: "Durazno amarillo",
  },
  { emoji: "🥑", unitWeight: 0.17, id: "avocado", unit: "unit", name: "Palta" },
  {
    emoji: "🫐",
    unitWeight: 0.3,
    id: "blueberry",
    unit: "unit",
    name: "Arándano",
  },
  {
    emoji: "🍒",
    unitWeight: 0.005,
    id: "cherry",
    unit: "kg",
    name: "Cereza",
  },
  {
    emoji: "🍇",
    unitWeight: 0.005,
    id: "grape_green",
    unit: "kg",
    name: "Uva verde",
  },
  {
    emoji: "🥝",
    unitWeight: 0.075,
    id: "kiwi",
    unit: "kg",
    name: "Kiwi",
  },
  {
    emoji: "🍋",
    unitWeight: 0.1,
    id: "lemon",
    unit: "kg",
    name: "Limón",
  },
  {
    emoji: "🍋",
    unitWeight: 0.05,
    id: "lime",
    unit: "kg",
    name: "Lima",
  },
  {
    emoji: "🥭",
    unitWeight: 0.2,
    id: "mango",
    unit: "unit",
    name: "Mango",
  },
  {
    emoji: "🍈",
    unitWeight: 1.8,
    id: "melon",
    unit: "unit",
    name: "Melón",
  },
  {
    emoji: "🍉",
    unitWeight: 9,
    id: "watermelon",
    unit: "unit",
    name: "Zandía",
  },
  {
    emoji: "🍑",
    unitWeight: 0.15,
    id: "nectarine",
    unit: "kg",
    name: "Pelón",
  },
  {
    emoji: "🍊",
    unitWeight: 0.13,
    id: "orange_juice",
    unit: "kg",
    name: "Naranja jugo",
  },
  {
    emoji: "🍊",
    unitWeight: 0.13,
    id: "orange",
    unit: "kg",
    name: "Naranja ombligo",
  },
  {
    emoji: "🍐",
    unitWeight: 0.18,
    id: "pear",
    unit: "kg",
    name: "Pera",
  },
  {
    emoji: "🍍",
    unitWeight: 1.6,
    id: "pineapple",
    unit: "unit",
    name: "Ananá",
  },
  {
    emoji: "❓",
    unitWeight: 0.065,
    id: "plum",
    unit: "kg",
    name: "Ciruela",
  },
  {
    emoji: "🍊",
    unitWeight: 0.12,
    id: "tangerine",
    unit: "kg",
    name: "Mandarina",
  },
].sort((a, b) => a.name.localeCompare(b.name));
